image: Visual Studio 2017
build: off
environment:
  MONACO_VERSION: 1.15
  BUILD_RESULT: monaco-$(MONACO_VERSION).zip
  MONACO_URL:
    secure: fhxf6GDTF+9AWJKuKiosKvtL5OGoCtpL76CbGPFx05F/fBGKirEssR768voD9wPrDHiHiTljpLRCtip3bStV59PGtXnlWGbTRBpeNiskJwA=

build_script:
    - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
    - ps: Invoke-WebRequest $env:MONACO_URL -OutFile monaco.zip
    - unzip monaco.zip
    - cd monaco/Source
      # Needs /bigobj to avoid
      # fatal error C1128: number of sections exceeded object file format limit
    - cl /O2 /bigobj /EHsc /Femonaco.exe *.cpp
    - cd ../..
    - 7z a %BUILD_RESULT% monaco\*.pdf monaco\*.ppt monaco\Source\monaco.exe

artifacts:
    - path: $(BUILD_RESULT)
